### This script was annotated with the help of generative AI with internet access ###

library(terra)
library(parallel)

# Set working directory 
wd <- "/lustre1/g/sbs_bonebrake/Eugene/map_validation" 
setwd(wd)

# Disable scientific notation for better readability
options(scipen = 999) 

# Define directories for Daru (2024) and our maps
PUB.dir <- "published_maps" # Existing directory with SDM maps produced by Daru (2024)
PUB.formatted.dir <- "formatted_published_maps" # New directory to hold formatted outputs of Daru (2024)
TA.dir <- "clipped_maps_biomod_4.2.4_datapp_2025" # Existing directory with SDM maps generated by this study
temp.dir <- "temp_maps" # New directory to temporarily store maps

# Specify ensemble model
EM <- "EMmean"

# Define study area
Xmini <- 69 #left x-axis
Xmaxi <- 161.6 #right x-axis
Ymini <- -10 #lower y-axis
Ymaxi <- 36 #upper y-axis

ncores = 8 # Number of cores available for parallel processing


########## Get common list of species being modelled by both studies ##########

file.list.published <- list.files(PUB.dir)
file.list.TA <- list.files(TA.dir)

sp.list.published <- gsub(".tif", "", file.list.published)
sp.list.TA <- gsub("_ensemble_TSSbin.tif", "", file.list.TA)
sp.list.TA <- gsub("\\.", " ", sp.list.TA)

common_list <- intersect(sp.list.published, sp.list.TA)
common.list <- gsub(" ", ".", common_list)


########## Format maps produced by Daru (2024) ##########

# Create a new directory for formatted maps
dir.create(paste0("/lustre1/g/sbs_bonebrake/Eugene/map_validation/",PUB.formatted.dir)) 

# Prepare for spatial analysis
Global <- terra::vect("/lustre1/g/sbs_bonebrake/Eugene/SDMin/world.shp")
Global <- terra::crop(Global,ext(Xmini,Xmaxi,Ymini,Ymaxi)) 

Global <- terra::project(Global,"epsg:6933") 
r.rast <- terra::rast(Global, resolution=c(10000,10000)) # Create a raster template
r <- terra::rasterize(Global, r.rast)
r0 <- subst(r, from = 1, to = 0)

### Function to format Daru (2024) maps by species
Formatmaps <- function(i) {
  map <- terra::rast(paste0(PUB.dir,"/",common_list[i],".tif"))
  map <- terra::project(map,"epsg:6933",method="near")
  r.map <- terra::resample(map, r0, method="near")
  values(r.map)[is.na(values(r.map))] <- 0
  std.map <- r.map+r0
  
  # Write the formatted map to the new directory
  terra::writeRaster(std.map, paste0("/lustre1/g/sbs_bonebrake/Eugene/map_validation/",
                                     PUB.formatted.dir,"/",common_list[i],".tif"), overwrite=TRUE)
}

# Execute formatting in parallel
i <- 1:length(common_list)
mclapply(i, Formatmaps, mc.cores=ncores) 


########## Map comparison ##########

### Diversity pattern
my_stack_PUB <- terra::rast(paste0(PUB.formatted.dir,"/",common_list,".tif"))
alpha_PUB <- terra::app(my_stack_PUB, fun=sum, cores=ncores)
plot(alpha_PUB) # Plot the butterfly diversity according to Daru (2024) models
terra::writeRaster(alpha_PUB, paste0("published_data_diversity.tif"), overwrite=TRUE)

my_stack_TA <- terra::rast(paste0(TA.dir,"/",common.list,"_ensemble_TSSbin.tif"))
my_stack_TA <- my_stack_TA[EM]
alpha_TA <- terra::app(my_stack_TA, fun=sum, cores=ncores)
plot(alpha_TA)  # Plot the butterfly diversity according to our models
terra::writeRaster(alpha_TA, paste0("ta_data_diversity.tif"), overwrite=TRUE)

### Paired difference (within species)
dir.create(paste0("/lustre1/g/sbs_bonebrake/Eugene/map_validation/",temp.dir)) # Create a temporary directory 

# Initialize a data frame to record differences
columns <- c("Species","TAmore","PUBmore","Totaldiff")
diff.df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(diff.df) <- columns

# Function to calculate differences between maps
spdiff <- function(i) {
  pub.map <- terra::rast(paste0(PUB.formatted.dir,"/",common_list[i],".tif"))
  ta.map <- terra::rast(paste0(TA.dir,"/",common.list[i],"_ensemble_TSSbin.tif"))[EM]
  
  TA.more <- pub.map<ta.map # Identify areas where our map shows presence while Daru (2024) shows absence
  TA.more.n <- sum(values(TA.more), na.rm=TRUE)
  PUB.more <- pub.map>ta.map # Identify areas where our map shows absence while Daru (2024) shows presence
  PUB.more.n <- sum(values(PUB.more), na.rm=TRUE)
  Total.diff.n <- TA.more.n+PUB.more.n # Total differences
  
  # Write results in the data frame
  sp.data <- list(common_list[[i]],TA.more.n,PUB.more.n,Total.diff.n)
  diff.df[nrow(diff.df)+1,] <<- sp.data
  
  # Write the difference maps to the temporary directory
  terra::writeRaster(TA.more, paste0("/lustre1/g/sbs_bonebrake/Eugene/map_validation/",
                                      temp.dir,"/",common_list[i],"_TAmore.tif"), overwrite=TRUE)
  terra::writeRaster(PUB.more, paste0("/lustre1/g/sbs_bonebrake/Eugene/map_validation/",
                                      temp.dir,"/",common_list[i],"_PUBmore.tif"), overwrite=TRUE)
}

# Apply the function to calculate differences
i <- 1:length(common_list)
lapply(i, spdiff)

### Stack and plot difference pattern
stack_TAmore <- terra::rast(paste0(temp.dir,"/",common_list,"_TAmore.tif"))
alpha_TAmore <- terra::app(stack_TAmore, fun=sum, cores=ncores)
plot(alpha_TAmore)
terra::writeRaster(alpha_TAmore, "stacked_TA_more.tif", overwrite=FALSE)

stack_PUBmore <- terra::rast(paste0(temp.dir,"/",common_list,"_PUBmore.tif"))
alpha_PUBmore <- terra::app(stack_PUBmore, fun=sum, cores=ncores)
plot(alpha_PUBmore)
terra::writeRaster(alpha_PUBmore, "stacked_PUB_more.tif", overwrite=FALSE)

alpha_TAmore <- terra::rast("stacked_TA_more.tif")
alpha_PUBmore <- terra::rast("stacked_PUB_more.tif")
alpha_diff <- alpha_TAmore-alpha_PUBmore
plot(alpha_diff)
terra::writeRaster(alpha_diff, "alpha_diff.tif", overwrite=FALSE)
